version = 1

[[annotations]]
path = [
    "build.py",
    "docs/**",
    "icons/**",
    "assets/**",
    "pinyin-ime/**",
    "scripts/**",
    "skins/**",
    "tools/**",
    "tsf-tip/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Kaixin IME contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "pinyin-ime/src/handwrite_lookup/*.rs",
]
precedence = "override"
SPDX-FileCopyrightText = "hanzi_lookup contributors"
SPDX-License-Identifier = "LGPL-3.0-only"

[[annotations]]
path = [
    "pinyin-ime/src/handwrite_lookup/data/mmah.bin",
]
precedence = "override"
SPDX-FileCopyrightText = "Make Me a Hanzi data authors"
SPDX-License-Identifier = "Arphic-1999"
