#pragma once
// Generated by scripts/generate_shared_contracts.py.
#include <cwchar>
namespace SrfConfigSchema {
namespace key {
inline constexpr wchar_t kTheme[] = L"theme";
inline constexpr wchar_t kCandidateMaterial[] = L"candidate_material";
inline constexpr wchar_t kCandidateDensity[] = L"candidate_density";
inline constexpr wchar_t kCandidateLayoutVariant[] = L"candidate_layout_variant";
inline constexpr wchar_t kCandidateVerticalLayoutVariant[] = L"candidate_vertical_layout_variant";
inline constexpr wchar_t kCandidateHorizontalLayoutVariant[] = L"candidate_horizontal_layout_variant";
inline constexpr wchar_t kCandidateReduceMotion[] = L"candidate_reduce_motion";
inline constexpr wchar_t kHighlightTypoCandidates[] = L"highlight_typo_candidates";
inline constexpr wchar_t kShowCandidateSource[] = L"show_candidate_source";
inline constexpr wchar_t kFullscreenDetection[] = L"fullscreen_detection";
inline constexpr wchar_t kFullscreenPolicy[] = L"fullscreen_policy";
inline constexpr wchar_t kCommitTransport[] = L"commit_transport";
inline constexpr wchar_t kGameProfile[] = L"game_profile";
inline constexpr wchar_t kOverlayAnchor[] = L"overlay_anchor";
inline constexpr wchar_t kOverlayOffsetX[] = L"overlay_offset_x";
inline constexpr wchar_t kOverlayOffsetY[] = L"overlay_offset_y";
inline constexpr wchar_t kOverlayScale[] = L"overlay_scale";
inline constexpr wchar_t kOverlayMonitor[] = L"overlay_monitor";
inline constexpr wchar_t kOverlayBackend[] = L"overlay_backend";
inline constexpr wchar_t kBuiltinGameList[] = L"builtin_game_list";
inline constexpr wchar_t kAutoSuggestAppOptions[] = L"auto_suggest_app_options";
inline constexpr wchar_t kGameProcesses[] = L"game_processes";
inline constexpr wchar_t kHotkeyScope[] = L"hotkey_scope";
inline constexpr wchar_t kNeverLearnProcesses[] = L"never_learn_processes";
inline constexpr wchar_t kNeverClipboardProcesses[] = L"never_clipboard_processes";
inline constexpr wchar_t kNeverCandidateProcesses[] = L"never_candidate_processes";
inline constexpr wchar_t kPrivacyEnabled[] = L"enabled";
}
namespace defaults {
inline constexpr wchar_t kTheme[] = L"auto";
inline constexpr wchar_t kCandidateMaterial[] = L"auto";
inline constexpr wchar_t kCandidateDensity[] = L"standard";
inline constexpr wchar_t kCandidateLayoutVariant[] = L"compact";
inline constexpr wchar_t kCandidateHorizontalLayoutVariant[] = L"classic";
inline constexpr wchar_t kFullscreenPolicy[] = L"show_ui";
inline constexpr wchar_t kCommitTransport[] = L"tsf";
}
namespace section {
inline constexpr wchar_t kStyle[] = L"style";
inline constexpr wchar_t kCompatibility[] = L"compatibility";
inline constexpr wchar_t kPrivacy[] = L"privacy";
}
struct Entry { const wchar_t* section; const wchar_t* key; const wchar_t* value; };
inline constexpr Entry entries[] = {
{L"diagnostics",L"log_level",L"error"},
{L"style",L"candidate_horizontal",L"1"},
{L"style",L"candidate_density",L"standard"},
{L"style",L"candidate_vertical_layout_variant",L"compact"},
{L"style",L"candidate_horizontal_layout_variant",L"classic"},
{L"compatibility",L"fullscreen_detection",L"1"},
{L"compatibility",L"fullscreen_policy",L"show_ui"},
{L"compatibility",L"game_input_mode",L"manual"},
{L"compatibility",L"commit_transport",L"tsf"},
{L"compatibility",L"builtin_game_list",L"1"},
{L"compatibility",L"auto_suggest_app_options",L"1"},
{L"privacy",L"never_learn_processes",L""},
{L"privacy",L"never_clipboard_processes",L""},
{L"privacy",L"never_candidate_processes",L""},
{L"clipboard",L"background_enabled",L"0"},
{L"clipboard",L"max_history_items",L"60"},
{L"clipboard",L"max_pinned_items",L"24"},
{L"clipboard",L"max_text_utf16_units",L"20000"},
{L"clipboard",L"max_age_days",L"0"},
{L"screenshot",L"hotkey",L"off"},
{L"screenshot",L"auto_save",L"1"},
{L"screenshot",L"save_dir",L""},
{L"screenshot",L"silent_copy_enabled",L"0"},
{L"screenshot",L"silent_copy_dir",L""},
{L"screenshot",L"name_pattern",L"{timestamp}"},
{L"screenshot",L"format",L"png"},
{L"screenshot",L"copy_after_capture",L"1"},
{L"screenshot",L"ocr_after_capture",L"0"},
{L"screenshot",L"translate_after_capture",L"0"},
{L"screenshot",L"mode",L"manual_region"},
{L"screenshot",L"confirm_on_release",L"0"},
{L"screenshot",L"show_instructions",L"1"},
{L"clipboard",L"hotkey",L"off"},
{L"tools",L"settings_hotkey",L"off"},
{L"tools",L"handwrite_hotkey",L"off"},
{L"tools",L"ocr_hotkey",L"off"},
{L"tools",L"translate_hotkey",L"off"},
{L"input",L"traditional_hotkey",L"off"},
{L"input",L"game_mode_hotkey",L"Ctrl+Shift+Alt+G"},
{L"input",L"temporary_ascii_hotkey",L"off"},
{L"input",L"shift_tap_hotkey",L"1"},
{L"input",L"candidate_number_select",L"1"},
{L"input",L"symbol_fullwidth",L"0"},
{L"input",L"shift_symbol_temporary_ascii",L"0"},
{L"input",L"page_minus_equal",L"1"},
{L"input",L"page_comma_period",L"1"},
{L"engine",L"retry_on_failure",L"1"},
{L"engine",L"long_lookup_soft_budget_ms",L"4"},
{L"general",L"config_version",L"13"},
{L"input",L"default_ascii",L"0"},
{L"general",L"global_ascii",L"0"},
{L"input",L"default_full_shape",L"0"},
{L"input",L"default_chinese_punct",L"1"},
{L"input",L"curly_punct",L"1"},
{L"input",L"auto_pair_punct",L"1"},
{L"input",L"number_fullwidth",L"0"},
{L"input",L"date_auto_format",L"1"},
{L"input",L"english_word_input",L"0"},
{L"input",L"traditional_output",L"0"},
{L"input",L"default_fuzzy_pinyin",L"0"},
{L"fuzzy",L"zh_z",L"1"},
{L"fuzzy",L"ch_c",L"1"},
{L"fuzzy",L"sh_s",L"1"},
{L"fuzzy",L"n_l",L"1"},
{L"fuzzy",L"f_h",L"1"},
{L"fuzzy",L"an_ang",L"1"},
{L"fuzzy",L"en_eng",L"1"},
{L"fuzzy",L"in_ing",L"1"},
{L"input",L"default_double_pinyin",L"0"},
{L"engine",L"jianpin",L"1"},
{L"engine",L"mixed_pinyin",L"1"},
{L"engine",L"mixed_pinyin_aggressive",L"0"},
{L"engine",L"v_assist",L"1"},
{L"input",L"symbol_toolbox",L"1"},
{L"input",L"emoji_input",L"1"},
{L"engine",L"u_mode",L"0"},
{L"engine",L"show_status_notifications",L"1"},
{L"correction",L"enabled",L"1"},
{L"style",L"inline_preedit",L"1"},
{L"style",L"enhanced_position",L"1"},
{L"style",L"paging_on_scroll",L"1"},
{L"style",L"candidate_page_size",L"9"},
{L"style",L"candidate_horizontal_count",L"5"},
{L"style",L"candidate_horizontal_compact",L"0"},
{L"style",L"candidate_font_size",L"16"},
{L"style",L"candidate_opacity",L"100"},
{L"style",L"candidate_reduce_motion",L"0"},
{L"style",L"candidate_font_weight",L"500"},
{L"style",L"candidate_selected_font_weight",L"600"},
{L"style",L"candidate_label_font_weight",L"600"},
{L"style",L"candidate_chip_font_weight",L"500"},
{L"style",L"candidate_topmost",L"1"},
{L"style",L"show_candidate_reading",L"0"},
{L"style",L"show_candidate_score",L"0"},
{L"style",L"show_mode_in_candidate_header",L"0"},
{L"style",L"candidate_abbreviate_length",L"64"},
{L"input",L"full_shape_hotkey",L"0"},
{L"input",L"punct_hotkey",L"0"},
{L"input",L"fuzzy_hotkey",L"0"},
{L"input",L"double_pinyin_hotkey",L"0"},
{L"input",L"candidate_left_click",L"1"},
{L"input",L"candidate_right_click",L"1"},
{L"input",L"page_pgup_pgdn",L"1"},
{L"screenshot",L"date_subdirs",L"0"},
{L"ocr",L"keep_alive",L"1"},
{L"tools",L"ocr_translate_keep_window",L"1"},
{L"ocr",L"screenshot_auto_save",L"1"},
{L"clipboard",L"candidate_preview_enabled",L"0"},
{L"clipboard",L"record_source_app",L"0"},
{L"clipboard",L"pinned_respects_max_age",L"1"},
{L"general",L"show_notifications_time",L"1200"},
{L"style",L"theme",L"auto"},
{L"style",L"candidate_material",L"auto"},
{L"engine",L"final_lookup_cache_capacity",L"128"},
{L"engine",L"learning_sensitivity",L"standard"},
{L"engine",L"long_lookup_min_first_batch_candidates",L"6"},
{L"engine",L"prefix_cache_capacity",L"384"},
{L"engine",L"short_lookup_cache_capacity",L"192"},
{L"engine",L"user_hotword_boost",L"standard"},
{L"general",L"show_notifications",L"true"},
{L"input",L"cn_en_hotkey",L"none"},
{L"input",L"double_pinyin_schema",L"builtin"},
{L"ocr",L"profile",L"balanced"},
{L"ocr",L"screenshot_name_pattern",L"ocr-{datetime}"},
{L"ocr",L"screenshot_save_dir",L""},
{L"privacy",L"enabled",L"0"},
{L"rank",L"lm_single_scale",L"3.350"},
{L"rank",L"w_phrase_path",L"0.160"},
{L"rank",L"w_single_lm",L"0.820"},
{L"screenshot",L"conflict_strategy",L"increment"},
{L"style",L"candidate_font_file",L"Microsoft YaHei"},
{L"style",L"candidate_skin_file",L""},
{L"style",L"highlight_typo_candidates",L"1"},
{L"style",L"show_candidate_source",L"0"},
{L"tools",L"ocr_result_action",L"show"},
{L"tools",L"ocr_translate_hotkey",L"off"},
{L"tools",L"translate_result_action",L"show"},
{L"tools",L"wintranslator_path",L""},
};
inline const wchar_t* DefaultValue(const wchar_t* section, const wchar_t* key) {
for (const auto& e : entries) if (_wcsicmp(e.section, section)==0 && _wcsicmp(e.key,key)==0) return e.value;
return nullptr;
}
}
