#pragma once

#include <guiddef.h>

EXTERN_C const GUID CLSID_SrfTsfTip;
EXTERN_C const GUID GUID_PROFILE_SRF;
EXTERN_C const GUID GUID_FUNCTION_SRF_CONFIGURE;

EXTERN_C const GUID GUID_DISPLAY_ATTRIBUTE_SRF_INPUT;

EXTERN_C const GUID GUID_COMPARTMENT_SRF_PUNCT;
EXTERN_C const GUID GUID_COMPARTMENT_SRF_FUZZY;
EXTERN_C const GUID GUID_COMPARTMENT_SRF_DOUBLE;

EXTERN_C const GUID GUID_PRESERVEDKEY_SRF_TOGGLE_IME;
EXTERN_C const GUID GUID_PRESERVEDKEY_SRF_TOGGLE_IME_CTRL_SPACE;
EXTERN_C const GUID GUID_PRESERVEDKEY_SRF_TOGGLE_FULLSHAPE;
EXTERN_C const GUID GUID_PRESERVEDKEY_SRF_TOGGLE_PUNCT;
EXTERN_C const GUID GUID_PRESERVEDKEY_SRF_TOGGLE_FUZZY;
EXTERN_C const GUID GUID_PRESERVEDKEY_SRF_TOGGLE_DOUBLE;
EXTERN_C const GUID GUID_PRESERVEDKEY_SRF_SCREENSHOT;
EXTERN_C const GUID GUID_PRESERVEDKEY_SRF_GAME_MODE;
EXTERN_C const GUID GUID_PRESERVEDKEY_SRF_TEMP_ASCII;
