// Generated by scripts/generate_shared_contracts.py.
pub mod section {
    pub const STYLE: &str = "style";
    pub const COMPATIBILITY: &str = "compatibility";
    pub const PRIVACY: &str = "privacy";
    pub const ENGINE: &str = "engine";
}
pub mod key {
    pub const THEME: &str = "theme";
    pub const CANDIDATE_MATERIAL: &str = "candidate_material";
    pub const CANDIDATE_DENSITY: &str = "candidate_density";
    pub const CANDIDATE_LAYOUT_VARIANT: &str = "candidate_layout_variant";
    pub const CANDIDATE_VERTICAL_LAYOUT_VARIANT: &str = "candidate_vertical_layout_variant";
    pub const CANDIDATE_HORIZONTAL_LAYOUT_VARIANT: &str = "candidate_horizontal_layout_variant";
    pub const CANDIDATE_REDUCE_MOTION: &str = "candidate_reduce_motion";
    pub const HIGHLIGHT_TYPO_CANDIDATES: &str = "highlight_typo_candidates";
    pub const SHOW_CANDIDATE_SOURCE: &str = "show_candidate_source";
    pub const LEARNING_SENSITIVITY: &str = "learning_sensitivity";
    pub const USER_HOTWORD_BOOST: &str = "user_hotword_boost";
    pub const FULLSCREEN_DETECTION: &str = "fullscreen_detection";
    pub const FULLSCREEN_POLICY: &str = "fullscreen_policy";
    pub const COMMIT_TRANSPORT: &str = "commit_transport";
    pub const GAME_PROFILE: &str = "game_profile";
    pub const OVERLAY_ANCHOR: &str = "overlay_anchor";
    pub const OVERLAY_OFFSET_X: &str = "overlay_offset_x";
    pub const OVERLAY_OFFSET_Y: &str = "overlay_offset_y";
    pub const OVERLAY_SCALE: &str = "overlay_scale";
    pub const OVERLAY_MONITOR: &str = "overlay_monitor";
    pub const OVERLAY_BACKEND: &str = "overlay_backend";
    pub const BUILTIN_GAME_LIST: &str = "builtin_game_list";
    pub const AUTO_SUGGEST_APP_OPTIONS: &str = "auto_suggest_app_options";
    pub const GAME_PROCESSES: &str = "game_processes";
    pub const NEVER_LEARN_PROCESSES: &str = "never_learn_processes";
    pub const NEVER_CLIPBOARD_PROCESSES: &str = "never_clipboard_processes";
    pub const NEVER_CANDIDATE_PROCESSES: &str = "never_candidate_processes";
    pub const PRIVACY_ENABLED: &str = "enabled";
    pub const PREFIX_CACHE_CAPACITY: &str = "prefix_cache_capacity";
    pub const FINAL_LOOKUP_CACHE_CAPACITY: &str = "final_lookup_cache_capacity";
    pub const SHORT_LOOKUP_CACHE_CAPACITY: &str = "short_lookup_cache_capacity";
    pub const LONG_LOOKUP_SOFT_BUDGET_MS: &str = "long_lookup_soft_budget_ms";
    pub const LONG_LOOKUP_MIN_FIRST_BATCH_CANDIDATES: &str = "long_lookup_min_first_batch_candidates";
    pub const GAME_INPUT_MODE: &str = "game_input_mode";
}
pub mod default {
    pub const THEME: &str = "auto";
    pub const CANDIDATE_MATERIAL: &str = "auto";
    pub const CANDIDATE_DENSITY: &str = "standard";
    pub const CANDIDATE_LAYOUT_VARIANT: &str = "compact";
    pub const CANDIDATE_HORIZONTAL_LAYOUT_VARIANT: &str = "classic";
    pub const FULLSCREEN_POLICY: &str = "show_ui";
    pub const COMMIT_TRANSPORT: &str = "tsf";
    pub const OVERLAY_ANCHOR: &str = "auto";
    pub const OVERLAY_SCALE_PERCENT: usize = 100;
    pub const OVERLAY_MONITOR: &str = "auto";
    pub const OVERLAY_BACKEND: &str = "auto";
    pub const LEARNING_SENSITIVITY: &str = "standard";
    pub const USER_HOTWORD_BOOST: &str = "standard";
    pub const PREFIX_CACHE_CAPACITY: usize = 384;
    pub const FINAL_LOOKUP_CACHE_CAPACITY: usize = 128;
    pub const SHORT_LOOKUP_CACHE_CAPACITY: usize = 192;
    pub const LONG_LOOKUP_SOFT_BUDGET_MS: usize = 4;
    pub const LONG_LOOKUP_MIN_FIRST_BATCH_CANDIDATES: usize = 6;
    pub const GAME_INPUT_MODE: &str = "manual";
    pub const GAME_MODE_HOTKEY: &str = "Ctrl+Shift+Alt+G";
}
pub mod options {
    pub const THEMES: &[&str] = &["auto", "light", "dark", "high_contrast"];
    pub const CANDIDATE_MATERIALS: &[&str] = &["auto", "solid", "gradient", "mist"];
    pub const CANDIDATE_DENSITIES: &[&str] = &["compact", "standard", "comfortable"];
    pub const CANDIDATE_LAYOUTS: &[&str] = &["classic", "compact", "card"];
    pub const FULLSCREEN_POLICIES: &[&str] = &["show_ui", "ascii", "hide_ui", "off"];
    pub const COMMIT_TRANSPORTS: &[&str] = &["auto", "tsf", "clipboard_paste", "unicode_sendinput"];
    pub const OVERLAY_ANCHORS: &[&str] = &[
        "auto",
        "caret",
        "top_left",
        "top_center",
        "top_right",
        "bottom_left",
        "bottom_center",
        "bottom_right",
    ];
    pub const OVERLAY_BACKENDS: &[&str] = &["auto", "in_process", "external"];
    pub const LEARNING_SENSITIVITY: &[&str] = &["conservative", "standard", "aggressive"];
    pub const USER_HOTWORD_BOOST: &[&str] = &["conservative", "standard", "strong", "aggressive"];
    pub const GAME_INPUT_MODES: &[&str] = &["manual", "passthrough", "chinese", "auto_text"];
}
pub const CONFIG_VERSION: usize = 14;
pub struct ConfigEntry { pub section: &'static str, pub key: &'static str, pub default: &'static str, pub kind: &'static str, pub options: &'static [&'static str] }
pub const ENTRIES: &[ConfigEntry] = &[
ConfigEntry { section: "diagnostics", key: "log_level", default: "error", kind: "string", options: &[] },
ConfigEntry { section: "style", key: "candidate_horizontal", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "style", key: "candidate_density", default: "standard", kind: "string", options: &["compact","standard","comfortable"] },
ConfigEntry { section: "style", key: "candidate_vertical_layout_variant", default: "compact", kind: "string", options: &[] },
ConfigEntry { section: "style", key: "candidate_horizontal_layout_variant", default: "classic", kind: "string", options: &[] },
ConfigEntry { section: "compatibility", key: "fullscreen_detection", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "compatibility", key: "fullscreen_policy", default: "show_ui", kind: "string", options: &["show_ui","ascii","hide_ui","off"] },
ConfigEntry { section: "compatibility", key: "game_input_mode", default: "manual", kind: "string", options: &["manual","passthrough","chinese","auto_text"] },
ConfigEntry { section: "compatibility", key: "commit_transport", default: "tsf", kind: "string", options: &["auto","tsf","clipboard_paste","unicode_sendinput"] },
ConfigEntry { section: "compatibility", key: "builtin_game_list", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "compatibility", key: "auto_suggest_app_options", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "privacy", key: "never_learn_processes", default: "", kind: "string", options: &[] },
ConfigEntry { section: "privacy", key: "never_clipboard_processes", default: "", kind: "string", options: &[] },
ConfigEntry { section: "privacy", key: "never_candidate_processes", default: "", kind: "string", options: &[] },
ConfigEntry { section: "clipboard", key: "background_enabled", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "clipboard", key: "max_history_items", default: "60", kind: "integer", options: &[] },
ConfigEntry { section: "clipboard", key: "max_pinned_items", default: "24", kind: "integer", options: &[] },
ConfigEntry { section: "clipboard", key: "max_text_utf16_units", default: "20000", kind: "integer", options: &[] },
ConfigEntry { section: "clipboard", key: "max_age_days", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "screenshot", key: "hotkey", default: "off", kind: "string", options: &[] },
ConfigEntry { section: "screenshot", key: "auto_save", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "screenshot", key: "save_dir", default: "", kind: "string", options: &[] },
ConfigEntry { section: "screenshot", key: "silent_copy_enabled", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "screenshot", key: "silent_copy_dir", default: "", kind: "string", options: &[] },
ConfigEntry { section: "screenshot", key: "name_pattern", default: "{timestamp}", kind: "string", options: &[] },
ConfigEntry { section: "screenshot", key: "format", default: "png", kind: "string", options: &[] },
ConfigEntry { section: "screenshot", key: "copy_after_capture", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "screenshot", key: "ocr_after_capture", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "screenshot", key: "translate_after_capture", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "screenshot", key: "mode", default: "manual_region", kind: "string", options: &[] },
ConfigEntry { section: "screenshot", key: "confirm_on_release", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "screenshot", key: "show_instructions", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "clipboard", key: "hotkey", default: "off", kind: "string", options: &[] },
ConfigEntry { section: "tools", key: "settings_hotkey", default: "off", kind: "string", options: &[] },
ConfigEntry { section: "tools", key: "handwrite_hotkey", default: "off", kind: "string", options: &[] },
ConfigEntry { section: "tools", key: "ocr_hotkey", default: "off", kind: "string", options: &[] },
ConfigEntry { section: "tools", key: "translate_hotkey", default: "off", kind: "string", options: &[] },
ConfigEntry { section: "input", key: "traditional_hotkey", default: "off", kind: "string", options: &[] },
ConfigEntry { section: "input", key: "game_mode_hotkey", default: "Ctrl+Shift+Alt+G", kind: "string", options: &[] },
ConfigEntry { section: "input", key: "temporary_ascii_hotkey", default: "off", kind: "string", options: &[] },
ConfigEntry { section: "input", key: "shift_tap_hotkey", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "candidate_number_select", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "symbol_fullwidth", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "shift_symbol_temporary_ascii", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "page_minus_equal", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "page_comma_period", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "engine", key: "retry_on_failure", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "engine", key: "long_lookup_soft_budget_ms", default: "4", kind: "integer", options: &[] },
ConfigEntry { section: "general", key: "config_version", default: "14", kind: "integer", options: &[] },
ConfigEntry { section: "input", key: "default_ascii", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "general", key: "global_ascii", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "default_full_shape", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "default_chinese_punct", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "curly_punct", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "auto_pair_punct", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "number_fullwidth", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "date_auto_format", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "english_word_input", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "traditional_output", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "default_fuzzy_pinyin", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "fuzzy", key: "zh_z", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "fuzzy", key: "ch_c", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "fuzzy", key: "sh_s", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "fuzzy", key: "n_l", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "fuzzy", key: "f_h", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "fuzzy", key: "an_ang", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "fuzzy", key: "en_eng", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "fuzzy", key: "in_ing", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "default_double_pinyin", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "engine", key: "jianpin", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "engine", key: "mixed_pinyin", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "engine", key: "mixed_pinyin_aggressive", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "engine", key: "v_assist", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "symbol_toolbox", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "emoji_input", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "engine", key: "u_mode", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "engine", key: "show_status_notifications", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "correction", key: "enabled", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "style", key: "inline_preedit", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "style", key: "enhanced_position", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "style", key: "paging_on_scroll", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "style", key: "candidate_page_size", default: "9", kind: "integer", options: &[] },
ConfigEntry { section: "style", key: "candidate_horizontal_count", default: "5", kind: "integer", options: &[] },
ConfigEntry { section: "style", key: "candidate_horizontal_compact", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "style", key: "candidate_font_size", default: "16", kind: "integer", options: &[] },
ConfigEntry { section: "style", key: "candidate_opacity", default: "100", kind: "integer", options: &[] },
ConfigEntry { section: "style", key: "candidate_reduce_motion", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "style", key: "candidate_font_weight", default: "500", kind: "integer", options: &[] },
ConfigEntry { section: "style", key: "candidate_selected_font_weight", default: "600", kind: "integer", options: &[] },
ConfigEntry { section: "style", key: "candidate_label_font_weight", default: "600", kind: "integer", options: &[] },
ConfigEntry { section: "style", key: "candidate_chip_font_weight", default: "500", kind: "integer", options: &[] },
ConfigEntry { section: "style", key: "candidate_topmost", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "style", key: "show_candidate_reading", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "style", key: "show_candidate_score", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "style", key: "show_mode_in_candidate_header", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "style", key: "candidate_abbreviate_length", default: "64", kind: "integer", options: &[] },
ConfigEntry { section: "input", key: "full_shape_hotkey", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "punct_hotkey", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "fuzzy_hotkey", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "double_pinyin_hotkey", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "candidate_left_click", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "candidate_right_click", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "input", key: "page_pgup_pgdn", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "screenshot", key: "date_subdirs", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "ocr", key: "keep_alive", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "tools", key: "ocr_translate_keep_window", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "ocr", key: "screenshot_auto_save", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "clipboard", key: "candidate_preview_enabled", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "clipboard", key: "record_source_app", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "clipboard", key: "pinned_respects_max_age", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "general", key: "show_notifications_time", default: "1200", kind: "integer", options: &[] },
ConfigEntry { section: "style", key: "theme", default: "auto", kind: "string", options: &["auto","light","dark","high_contrast"] },
ConfigEntry { section: "style", key: "candidate_material", default: "auto", kind: "string", options: &["auto","solid","gradient","mist"] },
ConfigEntry { section: "engine", key: "final_lookup_cache_capacity", default: "128", kind: "integer", options: &[] },
ConfigEntry { section: "engine", key: "learning_sensitivity", default: "standard", kind: "string", options: &[] },
ConfigEntry { section: "engine", key: "long_lookup_min_first_batch_candidates", default: "6", kind: "integer", options: &[] },
ConfigEntry { section: "engine", key: "prefix_cache_capacity", default: "384", kind: "integer", options: &[] },
ConfigEntry { section: "engine", key: "short_lookup_cache_capacity", default: "192", kind: "integer", options: &[] },
ConfigEntry { section: "engine", key: "user_hotword_boost", default: "standard", kind: "string", options: &[] },
ConfigEntry { section: "general", key: "show_notifications", default: "true", kind: "string", options: &[] },
ConfigEntry { section: "input", key: "cn_en_hotkey", default: "none", kind: "string", options: &[] },
ConfigEntry { section: "input", key: "double_pinyin_schema", default: "builtin", kind: "string", options: &[] },
ConfigEntry { section: "ocr", key: "profile", default: "balanced", kind: "string", options: &[] },
ConfigEntry { section: "ocr", key: "screenshot_name_pattern", default: "ocr-{datetime}", kind: "string", options: &[] },
ConfigEntry { section: "ocr", key: "screenshot_save_dir", default: "", kind: "string", options: &[] },
ConfigEntry { section: "privacy", key: "enabled", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "rank", key: "lm_single_scale", default: "3.350", kind: "string", options: &[] },
ConfigEntry { section: "rank", key: "w_phrase_path", default: "0.160", kind: "string", options: &[] },
ConfigEntry { section: "rank", key: "w_single_lm", default: "0.820", kind: "string", options: &[] },
ConfigEntry { section: "screenshot", key: "conflict_strategy", default: "increment", kind: "string", options: &[] },
ConfigEntry { section: "style", key: "candidate_font_file", default: "Microsoft YaHei", kind: "string", options: &[] },
ConfigEntry { section: "style", key: "candidate_skin_file", default: "", kind: "string", options: &[] },
ConfigEntry { section: "style", key: "highlight_typo_candidates", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "style", key: "show_candidate_source", default: "0", kind: "bool", options: &[] },
ConfigEntry { section: "tools", key: "ocr_result_action", default: "show", kind: "string", options: &[] },
ConfigEntry { section: "tools", key: "ocr_translate_hotkey", default: "off", kind: "string", options: &[] },
ConfigEntry { section: "tools", key: "translate_result_action", default: "show", kind: "string", options: &[] },
ConfigEntry { section: "tools", key: "wintranslator_path", default: "", kind: "string", options: &[] },
ConfigEntry { section: "tools", key: "translate_target_language", default: "auto-opposite", kind: "string", options: &[] },
ConfigEntry { section: "compatibility", key: "game_enter_behavior", default: "auto", kind: "string", options: &["auto","close","stay"] },
ConfigEntry { section: "compatibility", key: "game_auto_uia", default: "1", kind: "bool", options: &[] },
ConfigEntry { section: "compatibility", key: "game_status_indicator", default: "1", kind: "bool", options: &[] },
];
