"""Generate shared configuration and game contracts; --check rejects drift."""
import argparse, json, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
def render():
 s=json.loads((ROOT/'shared/config_schema.json').read_text(encoding='utf-8'))
 g=json.loads((ROOT/'shared/game_rules.json').read_text(encoding='utf-8'))
 defaults={(e['section'],e['key']):e['default'] for e in s['entries']}
 rs='// Generated by scripts/generate_shared_contracts.py.\n'
 for module, values in s['rust_modules'].items():
  rs+=f'pub mod {module} {{\n'
  for key,v in values.items():
   expr = (json.dumps(defaults[tuple(v["entry"])],ensure_ascii=False) if v["type"]=="&str" else defaults[tuple(v["entry"])]) if "entry" in v else v["expression"]
   rs+=f"    pub const {key}: {v['type']} = {expr};\n"
  rs+='}\n'
 rs+='pub const CONFIG_VERSION: usize = '+str(s['version'])+';\n'
 rs+="pub struct ConfigEntry { pub section: &'static str, pub key: &'static str, pub default: &'static str, pub kind: &'static str, pub options: &'static [&'static str] }\n"
 rs+='pub const ENTRIES: &[ConfigEntry] = &[\n'
 for e in s['entries']:
  q=lambda value:json.dumps(value,ensure_ascii=False)
  rs+='ConfigEntry { section: '+q(e['section'])+', key: '+q(e['key'])+', default: '+q(e['default'])+', kind: '+q(e['type'])+', options: &['+','.join(q(v) for v in e.get('options',[]))+'] },\n'
 rs+='];\n'
 cpp='#pragma once\n// Generated by scripts/generate_shared_contracts.py.\n#include <cwchar>\nnamespace SrfConfigSchema {\n'
 for ns,values in s['cpp_namespaces'].items():
  cpp+=f'namespace {ns} {{\n'
  for key,val in values.items():
   if ns=='defaults' and key in s['cpp_default_entries']:val=defaults[tuple(s['cpp_default_entries'][key])]
   cpp+=f'inline constexpr wchar_t {key}[] = L{json.dumps(val,ensure_ascii=False)};\n'
  cpp+='}\n'
 cpp+='struct Entry { const wchar_t* section; const wchar_t* key; const wchar_t* value; };\ninline constexpr Entry entries[] = {\n'
 for e in s['entries']:cpp+='{'+','.join('L'+json.dumps(e[x],ensure_ascii=False) for x in ['section','key','default'])+'},\n'
 cpp+='};\ninline const wchar_t* DefaultValue(const wchar_t* section, const wchar_t* key) {\nfor (const auto& e : entries) if (_wcsicmp(e.section, section)==0 && _wcsicmp(e.key,key)==0) return e.value;\nreturn nullptr;\n}\n}\n'
 ps='# Generated by scripts/generate_shared_contracts.py.\n$KaixinConfigVersion = '+str(s['version'])+'\nfunction Get-KaixinConfigDefaults {\n  @(\n'
 for e in s['entries']:ps+="    @{ Section = '"+e['section']+"'; Key = '"+e['key']+"'; Value = '"+e['default'].replace("'","''")+"' },\n"
 ps=ps.rstrip(',\n')+'\n  )\n}\n'
 game_rs='// Generated game process and window-class rules.\n'
 game_cpp='#pragma once\nnamespace SrfGameRules {\n'
 for key,name in [('processes','BUILTIN_GAME_PROCESSES'),('window_classes','BUILTIN_GAME_CLASSES')]:
  game_rs+=f'pub const {name}: &[&str] = &['+','.join(json.dumps(x) for x in g[key])+'];\n'
  game_cpp+=f'inline constexpr const wchar_t* {name}[] = {{'+','.join('L'+json.dumps(x) for x in g[key])+'};\n'
 game_cpp+='}\n'
 docs='# Generated configuration defaults\n\nEdit `shared/config_schema.json`, then run `python scripts/generate_shared_contracts.py`. Existing user values are preserved. Unknown keys remain available for extensions.\n\n| Section | Key | Default | Type | Options |\n|---|---|---|---|---|\n'
 for e in s['entries']:docs+='| '+' | '.join([e['section'],e['key'],e['default'].replace('|','\\|'),e['type'],', '.join(e.get('options',[]))])+' |\n'
 ini='; Generated defaults; existing configuration is not overwritten.\n'
 for section in dict.fromkeys(e['section'] for e in s['entries']):
  ini+=f'\n[{section}]\n'+''.join(e['key']+'='+e['default']+'\n' for e in s['entries'] if e['section']==section)
 retired=json.loads((ROOT/'shared/retired_optional_lexicons.json').read_text(encoding='utf-8'))
 if len(retired)!=len(set(retired)) or any(not tag or any(c not in 'abcdefghijklmnopqrstuvwxyz0123456789_' for c in tag) for tag in retired):
  raise ValueError('Invalid retired optional lexicon tags')
 retired_rs='// Generated by scripts/generate_shared_contracts.py.\n'
 retired_rs+='pub const RETIRED_OPTIONAL_LEXICON_TAGS: &[&str] = &['+','.join(json.dumps(tag) for tag in retired)+'];\n'
 retired_files=json.loads((ROOT/'shared/retired_lexicon_files.json').read_text(encoding='utf-8'))
 if any(Path(name).is_absolute() or '..' in Path(name).parts or len(Path(name).parts)!=2 or not name.endswith('.txt') for name in retired_files):
  raise ValueError('Invalid retired lexicon file paths')
 retired_rs+='pub const RETIRED_PACKAGED_LEXICON_FILES: &[&str] = &['+','.join(json.dumps(name,ensure_ascii=False) for name in retired_files)+'];\n'
 retired_iss='; Generated by scripts/generate_shared_contracts.py. Only retired optional files are removed.\n'
 for name in retired_files:
  retired_iss+='Type: files; Name: "{app}\\lexicon\\'+name.replace('/','\\')+'"\n'
 for directory in ('zh-ext','ext'):
  for tag in retired:
   for filename in (tag+'.txt','THUOCL_'+tag+'.txt','*__THUOCL_'+tag+'.txt'):
    retired_iss+='Type: files; Name: "{app}\\lexicon\\'+directory+'\\'+filename+'"\n'
 return {'crates/kaixin-common/src/config_schema.rs':rs,'tsf-tip/include/config_schema.h':cpp,'tsf-tip/installer/config_defaults.generated.ps1':ps,'crates/kaixin-common/src/game_rules.rs':game_rs,'tsf-tip/include/game_rules.generated.h':game_cpp,'docs/config_defaults.generated.md':docs,'shared/defaults.generated.ini':ini,'pinyin-ime/src/retired_lexicons.generated.rs':retired_rs,'tsf-tip/installer/retired_lexicons.generated.iss':retired_iss}
def main():
 check=argparse.ArgumentParser();check.add_argument('--check',action='store_true');args=check.parse_args();bad=[]
 for name,text in render().items():
  path=ROOT/name
  if args.check:
   if not path.exists() or path.read_text(encoding='utf-8-sig')!=text:bad.append(name)
  else:
   if path.exists() and path.read_text(encoding='utf-8-sig')==text:continue
   path.parent.mkdir(parents=True,exist_ok=True);path.write_text(text,encoding='utf-8-sig' if path.suffix=='.ps1' else 'utf-8')
 if bad:raise SystemExit('Generated contract drift: '+', '.join(bad))
 print('Shared contracts checked' if args.check else 'Shared contracts generated')
if __name__=='__main__':main()
