#!/usr/bin/env python3
"""Build the user-switchable zh-ext lexicons from traceable source fragments."""

from __future__ import annotations

from collections import OrderedDict
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "data_sources" / "lexicon_fragments" / "zh-ext"
OUTPUT_DIR = ROOT / "lexicon" / "zh-ext"


@dataclass(frozen=True)
class Category:
    title: str
    sources: tuple[str, ...]
    limit: int | None = None
    fixed_weight: int | None = None


CATEGORIES = OrderedDict(
    {
        "technology.txt": Category(
            "现代科技、互联网与编程",
            (
                "ai_and_machine_learning.txt",
                "internet_products.txt",
                "programming_frameworks.txt",
                "software_and_cloud.txt",
            ),
        ),
        "daily_communication.txt": Category(
            "聊天与办公沟通",
            ("chat_common_phrases.txt", "office_common_phrases.txt"),
        ),
        "geography_admin.txt": Category(
            "行政区划、国家与城市",
            (
                "china_prefecture_level_admin_333.txt",
                "county_admin_short_names_2024.txt",
                "world_countries_major_cities.txt",
            ),
        ),
        "hangzhou_local.txt": Category(
            "杭州本地生活与地理",
            (
                "hangzhou_admin.txt",
                "hangzhou_business.txt",
                "hangzhou_food_culture.txt",
                "hangzhou_landmarks_life.txt",
                "hangzhou_local_culture.txt",
                "hangzhou_metro_stations_262.txt",
                "hangzhou_new_places.txt",
                "hangzhou_public_services.txt",
                "hangzhou_transport.txt",
            ),
        ),
        "people_names.txt": Category(
            "姓氏与人物姓名",
            ("chinese_surnames.txt", "name1.txt"),
        ),
        "animals.txt": Category(
            "500 个世界常见动物",
            ("animal_common_5000.txt",),
            limit=500,
            fixed_weight=6_000,
        ),
        "medicine.txt": Category("常见药物", ("yaowu.txt",)),
    }
)


def parse_row(path: Path, line_number: int, line: str) -> tuple[str, str, int]:
    fields = [field.strip() for field in line.split("\t")]
    if len(fields) != 3 or not fields[0] or not fields[1]:
        raise ValueError(f"{path}:{line_number}: expected phrase<TAB>code<TAB>weight")
    try:
        weight = int(fields[2])
    except ValueError as exc:
        raise ValueError(f"{path}:{line_number}: invalid weight {fields[2]!r}") from exc
    if weight <= 0:
        raise ValueError(f"{path}:{line_number}: weight must be positive")
    return fields[0], " ".join(fields[1].split()), weight


def merge_category(category: Category) -> list[tuple[str, str, int]]:
    entries: OrderedDict[tuple[str, str], tuple[str, int]] = OrderedDict()
    for source_name in category.sources:
        path = SOURCE_DIR / source_name
        if not path.is_file():
            raise FileNotFoundError(f"missing zh-ext source fragment: {path}")
        for line_number, raw in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            phrase, code, weight = parse_row(path, line_number, line)
            entry_key = (phrase, code.casefold())
            previous = entries.get(entry_key)
            if previous is None:
                entries[entry_key] = (code, weight)
                continue
            _, previous_weight = previous
            if weight > previous_weight:
                entries[entry_key] = (code, weight)
    rows = [
        (phrase, code, weight)
        for (phrase, _), (code, weight) in entries.items()
    ]
    if category.limit is not None:
        rows = rows[: category.limit]
    if category.fixed_weight is not None:
        rows = [
            (phrase, code, category.fixed_weight)
            for phrase, code, _ in rows
        ]
    return rows


def write_category(path: Path, category: Category, rows: list[tuple[str, str, int]]) -> None:
    source_names = ", ".join(category.sources)
    text = (
        f"# 开心输入法扩展词库：{category.title}\n"
        "# 格式：词语<TAB>全拼或混合输入码<TAB>权重。\n"
        f"# Generated by scripts/merge_zh_ext_lexicons.py from: {source_names}\n"
    )
    text += "".join(f"{phrase}\t{code}\t{weight}\n" for phrase, code, weight in rows)
    path.write_text(text, encoding="utf-8", newline="\n")


def merge_lexicons() -> dict[str, int]:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    counts: dict[str, int] = {}
    for output_name, category in CATEGORIES.items():
        rows = merge_category(category)
        write_category(OUTPUT_DIR / output_name, category, rows)
        counts[output_name] = len(rows)
    return counts


def main() -> None:
    for output_name, count in merge_lexicons().items():
        print(f"{output_name}: {count} entries")


if __name__ == "__main__":
    main()
