"""Import the Android category snapshot into Windows, preserving provenance.

The Windows snapshot is self-contained after import: regeneration merges its
archived source fragments, so neither the Android project nor extra packages
are needed for normal Windows builds.
"""
import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path
import re
import shutil

ROOT = Path(__file__).resolve().parents[1]


def read_rows(path):
    rows = {}
    if not path.is_file() or path.name == 'single_char_common_8105.txt':
        return rows
    for line in path.read_text(encoding='utf-8-sig').splitlines():
        if not line.strip() or line.startswith('#'):
            continue
        columns = line.split('\t')
        if len(columns) < 3:
            continue
        word, raw = columns[:2]
        reading = ' '.join(re.split(r"[\s']+", raw.lower().replace('ü', 'v').replace('u:', 'v')))
        rows[(word, reading)] = max(rows.get((word, reading), 0), int(columns[2]))
    return rows


def group(category):
    if category in {'software', 'programming', 'ai', 'security', 'devices', 'photography', 'social_media'}:
        return '科技与开发'
    if category in {'proper_people', 'proper_organizations', 'brands', 'pets'}:
        return '名称与实体'
    if category == 'proper_places':
        return '地区词库 · 全国与世界'
    if category == 'pharmacy':
        return '药物名称'
    if category in {'law', 'finance', 'accounting', 'insurance', 'medical', 'architecture', 'manufacturing',
                    'energy', 'environment', 'math_statistics', 'physics_chemistry', 'biology', 'research',
                    'geography', 'history', 'philosophy', 'music', 'agriculture', 'warehousing'}:
        return '专业领域'
    return '日常表达'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--android-root', type=Path, required=True)
    args = parser.parse_args()
    source = args.android_root.resolve() / 'lexicon'
    upstream = json.loads((source / 'category-expansion.json').read_text(encoding='utf-8'))
    syllables = set((ROOT / 'pinyin-ime/data/syllables.txt').read_text(encoding='utf-8').split())
    before = set()
    for path in (ROOT / 'lexicon').rglob('*.txt'):
        # Previous imported category files are the managed output, not the baseline.
        if not path.name.startswith('category_'):
            before.update(read_rows(path))
    expected = {}
    catalog = []
    fragment_dir = ROOT / 'data_sources/lexicon_fragments/zh-ext'
    backup = ROOT / 'dist/windows-category-sync-before'
    for category in upstream['files']:
        relative = Path(category['file'])
        if relative.parent != Path('zh-ext') or not re.fullmatch(r'category_[a-z_]+\.txt', relative.name):
            raise ValueError(f'Invalid category path: {relative}')
        origin = source / relative
        fingerprint = hashlib.sha256(origin.read_bytes()).hexdigest()
        if fingerprint != category['sha256']:
            raise ValueError(f'Android category no longer matches its frozen report: {origin}')
        rows = read_rows(origin)
        if len(rows) != category['rows']:
            raise ValueError(f'Unexpected duplicate/count in {origin}')
        for (word, reading), score in rows.items():
            if len(word) != len(reading.split()) or any(s not in syllables for s in reading.split()) or not 1 <= score <= 10000:
                raise ValueError(f'Invalid Windows pinyin vocabulary: {word} {reading}')
            expected[(word, reading)] = max(expected.get((word, reading), 0), score)
        target = ROOT / 'lexicon' / relative
        fragment = fragment_dir / relative.name
        for destination in (target, fragment):
            if destination.is_file() and destination.read_bytes() != origin.read_bytes():
                saved = backup / destination.relative_to(ROOT)
                saved.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(destination, saved)
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(origin, destination)
        catalog.append({'tag': relative.stem, 'file': relative.name, 'title': category['title'],
                        'group': group(category['category']), 'rows': len(rows), 'default_enabled': True,
                        'sha256': fingerprint})
    for name in ('category-LICENSE.jieba.md', 'category-LICENSE.pypinyin.md', 'category-expansion.json'):
        shutil.copy2(source / name, ROOT / 'lexicon' / name)
    added = set(expected) - before
    manifest = {'schema_version': 1, 'source': 'Android categorized vocabulary snapshot',
                'categories': catalog}
    (ROOT / 'shared/category_lexicons.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    generated = ['// Generated by scripts/sync_android_category_lexicons.py from the frozen category manifest.',
                 'pub fn category_lexicon_info(tag: &str) -> Option<(&\'static str, &\'static str)> {',
                 '    match tag {']
    generated += [f'        "{entry["tag"]}" => Some(("{entry["title"]}", "{entry["group"]}")),' for entry in catalog]
    generated += ['        _ => None,', '    }', '}']
    (ROOT / 'pinyin-ime/src/category_lexicons.generated.rs').write_text('\n'.join(generated) + '\n', encoding='utf-8')
    report = {'category_count': len(catalog), 'source_category_rows': sum(c['rows'] for c in catalog),
              'source_unique_readings': len(expected), 'windows_added_readings': len(added),
              'windows_added_words': len({w for w, r in added} - {w for w, r in before}),
              'added_by_length': dict(sorted(Counter(len(w) for w, r in added).items())),
              'android_manifest_sha256': hashlib.sha256((source / 'category-expansion.json').read_bytes()).hexdigest(),
              'all_categories_enabled_by_default': True, 'files': catalog}
    (ROOT / 'lexicon/windows-category-import.json').write_text(json.dumps(report, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    notice = (f'Windows 分类词库扩充\n\n同步安卓 {len(catalog)} 个分类，收录 {len(expected):,} 条不同词语/读音。\n'
              f'相对 Windows 原词库新增 {len(added):,} 条读音记录、{report["windows_added_words"]:,} 个词语。\n'
              '保留分类基础词频、实际读音与原词库；新增分类默认开启，可在词库设置中独立开关。\n'
              '项目词表与请求短语由项目整理（生成式 AI 辅助）；语料补充来自 jieba 0.42.1，拼音来自 pypinyin 0.55.0。\n'
              '完整 MIT 许可随包保存在 category-LICENSE.jieba.md 和 category-LICENSE.pypinyin.md。\n'
              '来源快照、数量及哈希见 windows-category-import.json；源片段保存在 data_sources/lexicon_fragments/zh-ext/category_*.txt。\n\n'
              + '\n'.join(f"{c['title']}：{c['rows']:,} 条" for c in catalog) + '\n')
    (ROOT / 'lexicon/windows-category-import-notice.md').write_text(notice, encoding='utf-8')
    print(json.dumps({k: v for k, v in report.items() if k != 'files'}, ensure_ascii=False, indent=2))


if __name__ == '__main__':
    main()
